services:
  postgres:
    image: postgres:15-alpine
    container_name: job-tracker-shared-db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - job-tracker-shared-data:/var/lib/postgresql/data

volumes:
  job-tracker-shared-data:
    name: job-tracker-universal-storage