-- AlterTable
ALTER TABLE "Contact" ALTER COLUMN "email" DROP NOT NULL,
ALTER COLUMN "phoneNumber" DROP NOT NULL;

-- AlterTable
ALTER TABLE "Job" ALTER COLUMN "link" DROP NOT NULL,
ALTER COLUMN "description" DROP NOT NULL;
