import { HttpStatus } from '@nestjs/common';

export const BETTER_AUTH_ERROR_CODES = {
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  INVALID_PASSWORD: 'INVALID_PASSWORD',
  INVALID_EMAIL: 'INVALID_EMAIL',
  INVALID_EMAIL_OR_PASSWORD: 'INVALID_EMAIL_OR_PASSWORD',
  USER_ALREADY_EXISTS: 'USER_ALREADY_EXISTS',
  USER_ALREADY_EXISTS_USE_ANOTHER_EMAIL:
    'USER_ALREADY_EXISTS_USE_ANOTHER_EMAIL',
  EMAIL_NOT_VERIFIED: 'EMAIL_NOT_VERIFIED',
  SESSION_EXPIRED: 'SESSION_EXPIRED',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
} as const;

export const BETTER_AUTH_ERROR_CODE_MESSAGES: Record<string, string> = {
  [BETTER_AUTH_ERROR_CODES.USER_NOT_FOUND]: 'User not found',
  [BETTER_AUTH_ERROR_CODES.INVALID_PASSWORD]: 'Invalid password',
  [BETTER_AUTH_ERROR_CODES.INVALID_EMAIL]: 'Invalid email',
  [BETTER_AUTH_ERROR_CODES.INVALID_EMAIL_OR_PASSWORD]:
    'Invalid email or password',
  [BETTER_AUTH_ERROR_CODES.USER_ALREADY_EXISTS]: 'User already exists',
  [BETTER_AUTH_ERROR_CODES.USER_ALREADY_EXISTS_USE_ANOTHER_EMAIL]:
    'User already exists, use another email',
  [BETTER_AUTH_ERROR_CODES.EMAIL_NOT_VERIFIED]: 'Email not verified',
  [BETTER_AUTH_ERROR_CODES.SESSION_EXPIRED]: 'Session expired',
  [BETTER_AUTH_ERROR_CODES.TOKEN_EXPIRED]: 'Token expired',
  [BETTER_AUTH_ERROR_CODES.VALIDATION_ERROR]: 'Validation error',
};

export const BETTER_AUTH_STATUS_MAP: Record<string, number> = {
  [BETTER_AUTH_ERROR_CODES.USER_NOT_FOUND]: HttpStatus.NOT_FOUND,
  [BETTER_AUTH_ERROR_CODES.INVALID_PASSWORD]: HttpStatus.UNAUTHORIZED,
  [BETTER_AUTH_ERROR_CODES.INVALID_EMAIL]: HttpStatus.BAD_REQUEST,
  [BETTER_AUTH_ERROR_CODES.INVALID_EMAIL_OR_PASSWORD]: HttpStatus.UNAUTHORIZED,
  [BETTER_AUTH_ERROR_CODES.USER_ALREADY_EXISTS]: HttpStatus.CONFLICT,
  [BETTER_AUTH_ERROR_CODES.USER_ALREADY_EXISTS_USE_ANOTHER_EMAIL]:
    HttpStatus.CONFLICT,
  [BETTER_AUTH_ERROR_CODES.EMAIL_NOT_VERIFIED]: HttpStatus.FORBIDDEN,
  [BETTER_AUTH_ERROR_CODES.SESSION_EXPIRED]: HttpStatus.UNAUTHORIZED,
  [BETTER_AUTH_ERROR_CODES.TOKEN_EXPIRED]: HttpStatus.UNAUTHORIZED,
  [BETTER_AUTH_ERROR_CODES.VALIDATION_ERROR]: HttpStatus.BAD_REQUEST,

  BAD_REQUEST: HttpStatus.BAD_REQUEST,
  UNAUTHORIZED: HttpStatus.UNAUTHORIZED,
  FORBIDDEN: HttpStatus.FORBIDDEN,
  NOT_FOUND: HttpStatus.NOT_FOUND,
  METHOD_NOT_ALLOWED: HttpStatus.METHOD_NOT_ALLOWED,
  CONFLICT: HttpStatus.CONFLICT,
  UNPROCESSABLE_ENTITY: HttpStatus.UNPROCESSABLE_ENTITY,
};
