export const PRISMA_ERROR_CODES = {
  UNIQUE_CONSTRAINT_VIOLATION: 'P2002',
  FOREIGN_KEY_CONSTRAINT_VIOLATION: 'P2003',
  RECORD_NOT_FOUND: 'P2025',
  INTERNAL_SERVER_ERROR: 'internal_server_error',
};

export const PRISMA_ERROR_CODE_MESSAGES: Record<string, string> = {
  [PRISMA_ERROR_CODES.UNIQUE_CONSTRAINT_VIOLATION]:
    'Unique constraint violation',
  [PRISMA_ERROR_CODES.FOREIGN_KEY_CONSTRAINT_VIOLATION]:
    'Foreign key constraint violation',
  [PRISMA_ERROR_CODES.RECORD_NOT_FOUND]: 'Record not found',
  [PRISMA_ERROR_CODES.INTERNAL_SERVER_ERROR]: 'Internal server error',
};

export const PRISMA_STATUS_CODES = {
  [PRISMA_ERROR_CODES.UNIQUE_CONSTRAINT_VIOLATION]: 409, // Conflict
  [PRISMA_ERROR_CODES.FOREIGN_KEY_CONSTRAINT_VIOLATION]: 400, // Bad Request
  [PRISMA_ERROR_CODES.RECORD_NOT_FOUND]: 404, // Not Found
  [PRISMA_ERROR_CODES.INTERNAL_SERVER_ERROR]: 500, // Internal Server Error
};
