#!/bin/sh

echo "🚀 Parallel testing started..."

npx nx affected -t test --base=origin/main --head=HEAD --parallel=3 --watch=false --skip-nx-cache

if [ $? -ne 0 ]; then
  echo "❌ Test failed! Fix the code before pushing."
  exit 1
fi

echo "✅ Tests passed, push allowed."